### ISSUE TITLE
The Firestore class of the State doesn't support the databaseId field.

### ISSUE THREAD

**Issue by changsoo621** [GoogleCloudPlatform/memorystore-cluster-autoscaler#52]
# Issue
As the title, the Firestore class of the State in `state.js` file doesn't support the databaseId field.

So, I have created the PR to enable the injection of the databaseId field via configuration file, and as the follow up @henrybell created the PR to share better approach.

GCP team would you check this one?

# PRs
- https://github.com/GoogleCloudPlatform/memorystore-cluster-autoscaler/pull/44
- https://github.com/GoogleCloudPlatform/memorystore-cluster-autoscaler/pull/51

**Comment by henrybell** [comment]
Thanks @changsoo621 for raising the issue! One of my colleagues will review the PR shortly.

**Comment by henrybell** [comment]
Fixed in #51, so closing. Thanks again @changsoo621!
